"""Submit changed BoxBoxF1Fantasy URLs to IndexNow.

Run after deploying SEO/static page changes so participating search engines can
discover fresh URLs quickly. The IndexNow ownership key is generated by
14_build_seo_pages.py and hosted at the site root.

Examples:
    python pipeline/15_submit_indexnow.py --dry-run
    python pipeline/15_submit_indexnow.py
    python pipeline/15_submit_indexnow.py --url https://boxboxf1fantasy.com/picks/belgian-gp-2026/
"""
from __future__ import annotations

import argparse
import json
import runpy
import sys
import urllib.error
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
SEO_CONFIG = runpy.run_path(str(ROOT / "pipeline" / "14_build_seo_pages.py"))
SITE = SEO_CONFIG["SITE"]
WEB = SEO_CONFIG["WEB"]
INDEXNOW_KEY = SEO_CONFIG["INDEXNOW_KEY"]
KEY_LOCATION = f"{SITE}/{INDEXNOW_KEY}.txt"
DEFAULT_ENDPOINT = "https://api.indexnow.org/indexnow"

DISCOVERY_URLS = [
    f"{SITE}/llms.txt",
    f"{SITE}/llms-full.txt",
    f"{SITE}/search-index.json",
    f"{SITE}/openapi.json",
    f"{SITE}/data/",
    f"{SITE}/humans.txt",
    f"{SITE}/.well-known/security.txt",
]


def sitemap_urls(path: Path) -> list[str]:
    ns = {"sm": "http://www.sitemaps.org/schemas/sitemap/0.9"}
    root = ET.parse(path).getroot()
    urls = []
    for loc in root.findall(".//sm:loc", ns):
        if loc.text:
            urls.append(loc.text.strip())
    return urls


def unique_urls(urls: list[str]) -> list[str]:
    seen = set()
    out = []
    for url in urls:
        if url and url not in seen:
            seen.add(url)
            out.append(url)
    return out


def chunks(items: list[str], size: int):
    for i in range(0, len(items), size):
        yield items[i:i + size]


def submit_batch(endpoint: str, urls: list[str]) -> int:
    host = urlparse(SITE).netloc
    payload = {
        "host": host,
        "key": INDEXNOW_KEY,
        "keyLocation": KEY_LOCATION,
        "urlList": urls,
    }
    data = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        endpoint,
        data=data,
        headers={"Content-Type": "application/json; charset=utf-8"},
        method="POST",
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return response.status
    except urllib.error.HTTPError as exc:
        body = exc.read().decode("utf-8", errors="replace")
        raise RuntimeError(f"IndexNow returned HTTP {exc.code}: {body}") from exc


def main() -> int:
    parser = argparse.ArgumentParser(description="Submit BoxBoxF1Fantasy URLs to IndexNow.")
    parser.add_argument("--sitemap", type=Path, default=WEB / "sitemap.xml", help="Sitemap XML to read.")
    parser.add_argument("--endpoint", default=DEFAULT_ENDPOINT, help="IndexNow endpoint.")
    parser.add_argument("--url", action="append", default=[], help="Submit a specific URL. Repeatable.")
    parser.add_argument("--include-discovery", action="store_true", help="Also submit LLM/API/discovery endpoints.")
    parser.add_argument("--batch-size", type=int, default=10000, help="URLs per POST, max 10000 by protocol.")
    parser.add_argument("--dry-run", action="store_true", help="Print the payload summary without submitting.")
    args = parser.parse_args()

    if not (WEB / f"{INDEXNOW_KEY}.txt").exists():
        raise SystemExit(f"Missing IndexNow key file: {WEB / f'{INDEXNOW_KEY}.txt'}")
    if not args.url and not args.sitemap.exists():
        raise SystemExit(f"Missing sitemap: {args.sitemap}")
    if args.batch_size < 1 or args.batch_size > 10000:
        raise SystemExit("--batch-size must be between 1 and 10000")

    urls = list(args.url) if args.url else sitemap_urls(args.sitemap)
    if args.include_discovery:
        urls.extend(DISCOVERY_URLS)
    urls = unique_urls(urls)

    print(f"IndexNow endpoint: {args.endpoint}")
    print(f"Key location: {KEY_LOCATION}")
    print(f"URLs: {len(urls)}")

    if args.dry_run:
        for url in urls[:20]:
            print(f"  {url}")
        if len(urls) > 20:
            print(f"  ... {len(urls) - 20} more")
        return 0

    accepted = 0
    for batch in chunks(urls, args.batch_size):
        status = submit_batch(args.endpoint, batch)
        if status not in (200, 202):
            raise RuntimeError(f"Unexpected IndexNow status: {status}")
        accepted += len(batch)
        print(f"Submitted {len(batch)} URL(s), HTTP {status}")

    print(f"IndexNow submission complete: {accepted} URL(s)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
